# Generated by Django 6.1 on 2026-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_rename_subcategory_name_subcategory_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(upload_to='subcategory_images/'),
        ),
    ]
