# Generated by Django 6.1 on 2026-09-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0005_alter_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='product_image',
            new_name='product_images',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Subcategory_name',
            new_name='SubCategory_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Subcategory_name_en',
            new_name='SubCategory_name_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Subcategory_name_ru',
            new_name='SubCategory_name_ru',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='avito_app.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='avito_app.product'),
        ),
    ]
